# Generated by Django 5.1.5 on 2025-01-19 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH_DEP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Interim', 'Intérim')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_limite', models.DateField()),
                ('statut', models.CharField(default='Ouvert', max_length=20)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes', to='RH_DEP.service')),
            ],
        ),
    ]
